### ISSUE TITLE
Implement pruning of backups

### ISSUE THREAD

**Issue by aknuds1** [muzhack/muzhack-cronjobs#1]
In the backup script, delete backups that are older than 100 days.

Suggested algorithm:
1. List objects in backup bucket ([listObjects](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property))
2. For each object that has a modification date older than 100 days, delete it ([deleteObject](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteObject-property))

**Comment by hkwid** [comment]
``` python
import boto3
import datetime as dt

s3 = boto3.resource('s3')
retention_period = 100

bucket = s3.Bucket('bucket-name')

# check each file if it is expired or not
for object in bucket.objects.all():
    gap = dt.datetime.now(dt.timezone.utc) - object.last_modified

    if gap.days > retention_period:
        object.delete()
```
